app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, PasswordField
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms.validators import DataRequired, Email
from werkzeug.utils import secure_filename
from .. import document

class SignUp(FlaskForm):
	name = StringField('Your Name (First & Last)', validators=[DataRequired()])
	email = StringField('Email', validators=[DataRequired(), Email()])
	password = PasswordField('Password', validators=[DataRequired()])
	ssn = StringField('Social Security Number (Last 4 digits)', validators=[DataRequired()])
	pdf_file = FileField('Scanned document of your Driving License', validators=[FileRequired(), FileAllowed(document, '.doc file Only')])
	submit = SubmitField('Apply')

class Login(FlaskForm):
	email = StringField('Email', validators=[DataRequired(), Email()])
	password = PasswordField('Password', validators=[DataRequired()])
	submit = SubmitField('Login')

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import render_template, flash, redirect, url_for, session, send_file
from forms import SignUp, Login
from flask_login import login_required, login_user, logout_user
from . import home
from .. import document, db
from ..models import User, PassResets
@home.route('/')
def homepage():
	return render_template('home/index.html')

@home.route('/apply', methods=['GET','POST'])
def apply():
	form = SignUp()
	if form.validate_on_submit():
		try:
			filename = document.save(form.pdf_file.data)
			url = document.url(filename)
			user = User(email = form.email.data, full_name = form.name.data,
			    	    password = form.password.data, ssn = form.ssn.data)
			db.session.add(user)
			db.session.commit()
			flash('Your application has been submitted. You may now login but you will not be able to use the account until it is approved.')
			return redirect(url_for('home.homepage'))
		except:
			flash('Something went wrong during registration')
			return render_template('home/index.html')
	return render_template('home/apply.html', form = form)

@home.route('/login', methods=['GET','POST'])
def login():
	form = Login()
	if form.validate_on_submit():
		user = User.query.filter_by(email = form.email.data).first()
		if user is not None and user.verify_password( form.password.data ):
			login_user(user)
			return redirect(url_for('users.profile'))
		else:
			flash('Invalid login. Check to make sure your email and password matches')
	return render_template('home/login.html', form = form, title='Login')

app/templates/home/apply.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
Apply
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        {{ utils.flashed_messages() }}
        <div class="center">
            <h1><center>Apply</center></h1>
            <br/>
	    {% if current_user.is_authenticated %}
		<h4>Sorry, you are already registered. You cannot apply when logged in</h4>
	    {% else %}
            {{ wtf.quick_form(form) }}
	    {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/index.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="container">
<div class="content-section">
<div class="jumbotron">
<h1>Welcome</h1>
{{ utils.flashed_messages() }}
<p>Welcome to Bank Crouscant, where you can easily start the first steps in your financial journey. We provide different services to make our customers feel welcome and have a successful financial condition.</p>
<p>Some of our services are as follows:</p>
<ul>
<li>Cheap Credit Card services: You will easily get approved for one of the most advanced and secure credit card system. Our minimum credit card balance starts from $5000 and maximum is $10,000</li>
<li>Reliable locker security: We have secure lockers in place to keep your expensive materials like golds.</li>
<li>Reliable Mortgage: We will give you good mortgage loan to buy a house and have a great time with your family.</li>
</ul>
<p><center>So what are you waiting for? Apply now and hear back within 24 hours</p>
<a href="{{ url_for('home.apply') }}" role="button" class="btn btn-primary">Apply</a></center>
</div></div></div>
{% endblock %}

app/templates/home/login.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
Login
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        {{ utils.flashed_messages() }}
        <div class="center">
            <h1><center>Login</center></h1>
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}