app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, PasswordField, HiddenField
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms.validators import DataRequired, Email
from werkzeug.utils import secure_filename
from .. import document

class EditForm(FlaskForm):
	name = StringField('Your Name (First & Last)', validators=[DataRequired()])
	email = StringField('Email', validators=[DataRequired(), Email()])
	submit = SubmitField('Update Data')


class SendMoney(FlaskForm):
	sender = HiddenField('Sender', validators=[DataRequired()])
	receiver = IntegerField('User ID of the receiver', validators=[DataRequired()])
	amount = IntegerField('Amount being transferred', validators=[DataRequired()])
	submit = SubmitField('Send Money')

class ProfileImage(FlaskForm):
	url = StringField('Image link', validators=[DataRequired()])
	submit = SubmitField('Add profile picture')

app/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

from . import views

app/users/views.py
from flask import render_template, flash, redirect, url_for, session, send_file
from flask_login import login_required, login_user, current_user
from forms import EditForm, SendMoney, ProfileImage
from . import users
from .. import document, db
from ..models import User, PassResets
import urllib

# function to check if user is verified
def userVerified():
	is_verified = current_user.is_verified
	if is_verified == 1:
		return True
	else:
		return False

def validate_type(url):
	# check if content-type is jpeg
	headers = urllib.urlopen(url).headers
	if headers['Content-Type'] != 'image/jpeg':
		return False
	else:
		return True


#user profile page - contains simple info: Name, SSN, Balance
@users.route('/profile')
@login_required
def profile():
	return render_template('users/profile.html')

def add_balance(id, amount):
        receive_query = User.query.get(id)
        current_balance = receive_query.balance
        new_balance = amount + current_balance
        receive_query.balance = new_balance
        db.session.commit()

def remove_balance(id, amount):
        send_query = User.query.get(id)
        current_balance = send_query.balance
        new_balance = current_balance - amount
        send_query.balance = new_balance
        db.session.commit()


#modifying user profile 
@users.route('/edit/<string:id>', methods=['GET','POST'])
@login_required
def profile_edit(id):
	form = EditForm()
	user = User.query.get(id)
	if form.validate_on_submit():
		try:
			new_email = form.email.data
			update_email = User.query.filter_by(id=id).update(dict(email=new_email))
			update_name = User.query.filter_by(id=id).update(dict(full_name=form.name.data))
			db.session.commit()
			flash('Edit successful')
			return redirect(url_for('users.profile'))
		except:
			flash('Something went wrong')
	form.email.data = user.email
	form.name.data = user.full_name
	return render_template('/users/modify.html', form = form)


@users.route('/send', methods=['GET','POST'])
@login_required
def send_money():
	form = SendMoney()
	if form.validate_on_submit():
		try:
			receiver_id = form.receiver.data
			transfer_amount = form.amount.data
			sender_id = form.sender.data
			# check if sender can send money
			send_query = User.query.get(sender_id)
			if transfer_amount > send_query.balance:
				flash("You do not have enough balance")
				return redirect(url_for('users.profile'))
			else: 
				add_balance(receiver_id, transfer_amount)
				remove_balance(sender_id, transfer_amount)
				flash('Money transfer successful')
				return redirect(url_for('users.profile'))
		except:
			flash('Something went wrong')
			return redirect(url_for('users.profile'))
	form.sender.data = current_user.id
	return render_template('users/send.html', form = form)





@users.route('/image', methods=['GET','POST'])
@login_required
def profile_image():
	form = ProfileImage()
	if form.validate_on_submit():
		link = form.url.data
		if validate_type(link):
			user = User.query.get(current_user.id)
			user.profile_image = link
			db.session.commit()
			flash("Profile picture updated")
		else:
			flash("Image is not JPEG")
	return render_template('users/image.html', form=form)

app/templates/users/image.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
Profile Image
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        {{ utils.flashed_messages() }}
        <div class="center">
            <h1><center>Change Profile picture</center></h1>
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/users/modify.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
Login
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        {{ utils.flashed_messages() }}
        <div class="center">
            <h1><center>Edit Profile</center></h1>
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/users/profile.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
User Profile
{% endblock %}
{% block body %}
<div class="content-section">
{{ utils.flashed_messages() }}
<div class="container">
<div class="row">
	<div class="col-sm">
		<div class="panel panel-default">
			<div class="panel-heading">User information <a href="{{ url_for('users.profile_edit', id=current_user.id) }}"><i class="fa fa-pencil"></i></a></div>
			<div class="panel-body">
				<p><u>Full name</u>: {{ current_user.full_name }}</p>
				<p><u>Email</u>: {{ current_user.email }}</p>
				<p><u>SSN (Last 4 digits)</u>: {{ current_user.ssn }}</p>
			</div>
		</div>
	</div>
	{% if current_user.is_verified != 0 %}
	<div class="col-sm">
		<div class="panel panel-default">
			<div class="panel-heading">Balance</div>
			<div class="panel-body">
				<p><u>Total Balance</u>: ${{ current_user.balance }}</p>
				<p><u>Credit limit</u>: {{ current_user.credit_limit }}</p>
				<p><u>Card Number</u>: {{ current_user.card_number }}</p>
			</div>
		</div>
	</div>
	<a href="{{ url_for('users.send_money') }}" class="btn btn-primary" role="button">Send Money</a>
	{% endif %}
	<center>
		<img src="{{current_user.profile_image}}" width=50%, height=50%>
		<a href="{{ url_for('users.profile_image') }}" class="btn btn-primary" role="button">Change Profile</a>
	</center>
</div>
</div>
{% endblock %}

app/templates/users/send.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
Send Money
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        {{ utils.flashed_messages() }}
        <div class="center">
            <h1><center>Send Money</center></h1>
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}